import { start } from './lib.mjs';
const t = await start(); const { p } = t;
await t.go('/lambda/create');
await p.fill('#name', 'ui-fn');
const code = await p.inputValue('#code');
t.ok(code.includes('lambda_handler'), 'sample python code prefilled');
await p.selectOption('#runtime', 'nodejs22.x');
t.ok((await p.inputValue('#handler')) === 'index.handler' && (await p.inputValue('#code')).includes('export const handler'), 'runtime switch swaps handler + sample');
await p.selectOption('#runtime', 'python3.12');
await p.fill('#env', 'GREETING=hello\nMODE=test');
await t.submit('button:has-text("Create function")');
t.ok(p.url().endsWith('/lambda/ui-fn') && (await t.flash()).includes('Successfully created'), 'create: ' + await t.flash());
await t.go('/lambda/ui-fn?tab=code');
await p.waitForSelector('textarea[name=text]');
const src = await p.inputValue('textarea[name=text]');
t.ok(src.includes('Hello from LocalEmu'), 'code tab shows source extracted from the zip');
await p.fill('textarea[name=text]', src.replace('Hello from LocalEmu', 'Hello EDITED'));
await t.submit('button:has-text("Deploy")');
t.ok((await t.flash()).includes('Deployed'), 'deploy: ' + await t.flash());
t.ok((await p.inputValue('textarea[name=text]')).includes('Hello EDITED'), 'edited code persisted');
await t.go('/lambda/ui-fn?tab=configuration');
t.ok((await p.inputValue('#env')).includes('GREETING=hello'), 'env vars shown');
await p.fill('#memory', '256'); await t.submit('button:has-text("Save")');
t.ok((await t.flash()).includes('Configuration updated'), 'config update: ' + await t.flash());
await t.go('/lambda');
t.ok((await p.locator('tr[data-row]:has-text("ui-fn")').innerText()).includes('256 MB'), 'list shows new memory');
await t.go('/lambda/ui-fn?tab=test');
await p.click('button:has-text("Invoke")'); await p.waitForLoadState('load');
await p.waitForTimeout(500);
console.log('INVOKE (no docker here):', (await p.locator('main').innerText()).replace(/\s+/g, ' ').slice(0, 300));
await t.go('/lambda'); await t.confirmAction('ui-fn', 'Delete', 'delete');
t.ok((await p.locator('tr[data-row]:has-text("ui-fn")').count()) === 0, 'deleted');
await t.done();
